name: Deploy Backend to Production

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Run tests
        working-directory: ./backend
        run: |
          go test -v ./...

  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build
        working-directory: ./backend
        run: |
          go build -o app cmd/api/main.go

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend-app
          path: backend/app

  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: backend-app
          path: ./backend

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        env:
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USER: ${{ secrets.VPS_USER }}
        run: |
          # Copy files to VPS
          scp -r backend/* $VPS_USER@$VPS_HOST:/var/www/perjalanan-dinas/backend/

          # Restart service
          ssh $VPS_USER@$VPS_HOST << 'EOF'
            cd /var/www/perjalanan-dinas/backend
            chmod +x app
            sudo systemctl restart perjalanan-dinas
            sudo systemctl status perjalanan-dinas
          EOF

      - name: Health check
        run: |
          sleep 10
          curl -f https://api.yourdomain.com/health || exit 1
